package models

import "time"

// Job status constants. Using typed constants prevents accidental assignment of arbitary strings

const (
	StatusPending    = "pending"
	StatusProcessing = "processing"
	StatusCompleted  = "completed"
	StatusFailed     = "failed"
)

// Job represents a single email-sending task.
// Struct tas:
//
//	json: controls JSON field names (right side : REST API)
//	db: would be for sqlx, but we're using sqlite3 directly, so omit

type Job struct {
	ID         string `json:"id"` // UUID string, generated by us
	ToEmail    string `json:"to"` // recipient
	Subject    string `json:"subject"`
	Body       string `json:"body"`
	Status     string `json:"status"`
	RetryCount int    `json:"retry_count"` // how mant times we're retried
	MaxRetries int    `json:"max_retries"` // from config , r.g., 3

	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	ProcessedAt  *time.Time `json:"processed_at,omitempty"`   // nil if not processed
	ErrorMessage string     `json:"errror_message,omitempty"` // only set on failure
}
